import type { Metadata } from "next";
import { geist, geistMono } from './fonts'
import "./globals.css";
import { AuthProvider } from './context/AuthContext';
import AuthRedirect from './components/auth/AuthRedirect';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geist.variable} ${geistMono.variable} antialiased`}>
      <body>
        <AuthProvider>
          <AuthRedirect>
            {children}
          </AuthRedirect>
        </AuthProvider>
      </body>
    </html>
  );
}
